version: '3.8'

services:
  n8n:
    build: .
    ports:
      - 5678:5678
    restart: always
    environment:
      - N8N_LOG_LEVEL=debug
      - N8N_METRICS=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpass
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=pg-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=password
      - DB_QDRANT_HOST=qdrant
      - DB_QDRANT_PORT=6333
    depends_on:
      - pg-n8n
      - qdrant
    volumes:
      - n8n_data:/home/node/.n8n

  pg-n8n:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_n8n_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant_config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pg_n8n_data:
  qdrant_data:
  n8n_data:

configs:
  qdrant_config:
    file: ./Qdrant/config.yaml
